stages:
  - build
  - deploy

docker-build-borbland:
  image: docker:latest
  stage: build
  tags:
    - borblanding
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - mv Dockerfile Dockerfile
    - docker build -t registry.gitlab.com/av.pashintsev/borbflanding:latest .
    - docker push registry.gitlab.com/av.pashintsev/borblanding:latest
  only:
    - master

docker-run-borbfront:
  image: docker:latest
  stage: deploy
  tags:
    - borblanding
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker pull registry.gitlab.com/av.pashintsev/landing:latest
    - docker stop borbland || true
    - docker rm borbland || true
    - docker run -d --name borbland --restart=always 
      -p 3002:3000
      registry.gitlab.com/av.pashintsev/landing:latest
  when: manual
  only:
    - master