stages:
  - build

docker-build-borbland:
  image: docker:latest
  stage: build
  tags:
    - borb
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/av.pashintsev/borbflanding:latest .
    - docker push registry.gitlab.com/av.pashintsev/borblanding:latest
  only:
    - master
